function matrix = rotx(phi)
    % phi must be in radians
    matrix = [1     0           0           ;   ...
              0     cos(phi)    -sin(phi)   ;   ...
              0     sin(phi)    cos(phi)    ]   ;
end
